void displayPlots() {
  noFill();
  rect(WINDOW_LEFT_COLUMN + 2 * MARGIN, PRODUCT_PLOT_Y, WINDOW_RIGHT_COLUMN, PLOT_HEIGHT);
  rect(WINDOW_LEFT_COLUMN + 2 * MARGIN, STOCK_PLOT_Y, WINDOW_RIGHT_COLUMN, PLOT_HEIGHT);
  rect(WINDOW_LEFT_COLUMN + 2 * MARGIN, DATE_PICKER_Y, WINDOW_RIGHT_COLUMN, DATE_PICKER_HEIGHT);
}
